name: Build Release And Deploy Metadata

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 0 1,16 * *"

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: metadata-release-pages
  cancel-in-progress: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Compile dats
        run: bun ./compilers/compile-dats.js

      - name: Compile switch
        run: bun ./compilers/compile-switch.js

      - name: Compile discord-execs
        run: bun ./compilers/compile-discord-execs.js

      - name: Compile wine-execs
        run: bun ./compilers/compile-wine-execs.js

      - name: Compile all-execs
        run: bun ./compilers/compile-all-execs.js

      # - name: Build launchbox gamesdb submodule
      #   run: cd ./libretro-roms-scraper && bun install && bun run index.js
      # - name: Compile launchbox gamesdb
      #   run: bun ./compilers/compile-launchbox-gamesdb.js
      - name: Prepare build bundle
        run: |
          mkdir ./output/build
          cp ./output/all-execs.json ./output/build/all-execs.json
          cp ./output/all-serials.json ./output/build/all-serials.json
          cp ./output/all-sizes.json ./output/build/all-sizes.json
          zip -r ./output/build.zip ./output/
        #   cp ./output/libretro-full-database.json ./output/build/libretro-full-database.json
        #   cp ./output/libretro-index.json ./output/build/libretro-index.json

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: metadata-${{ github.run_number }}
          target_commitish: ${{ github.sha }}
          name: "Metadata build #${{ github.run_number }}"
          make_latest: "true"
          fail_on_unmatched_files: true
          files: |
            output/build.zip
            output/all-execs.json
            output/all-execs-raw.json
            output/all-serials.json
            output/all-sizes.json
        #   output/libretro-full-database.json
        #   output/libretro-index.json
        #    output/libretro-gamesdb/*.json

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-release

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
